[package]
name = "brainfuck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "brainfuck"
path = "src/cli.rs"
test = false
bench = false

[dependencies]
structopt = "0.3"