name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt update
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: run bf tests (skiping inputs)
      run: |
        cargo run -- test/add_and_sub.b -vvv
        cargo run -- test/crazy.b -vvv
        cargo run -- test/debug_symbol.b -vvv
        cargo run -- test/loops.b -vvv
        cargo run -- test/move_boundaries.b -vvv
        cargo run -- test/right_and_left.b -vvv
        cargo run -- test/long.b -vvv


    - name: run bf examples
      run: |
        cargo run -- examples/factorial.b
        cargo run -- examples/hello-world.b
        cargo run -- examples/hello-world2.b
        cargo run -- examples/squares.b
        cargo run -- examples/sum.b